[service]
address = "localhost:8080"

[logger]
level = "DEBUG"

[database]
in-memory = true # use in memory database
url       = "postgresql://postgres@localhost:5432/state"

[signer]
private-key = ""
